biome/forms.py
#!/usr/bin/env python3

from flask.ext.wtf import Form
from wtforms import (   BooleanField, 
                        DecimalField, 
                        HiddenField, 
                        IntegerField, 
                        RadioField, 
                        SelectField, 
                        StringField, 
                        SubmitField, 
                        TextAreaField, 
                        validators, 
                    )
from flask_wtf.file import FileField, FileRequired

class DatasetUploadForm(Form):

    ''' DatasetUploadForm is a WTForm Form object for uploading data files
    '''

    dataset_name = StringField('Dataset name:', [validators.Required(), validators.length(max=60)])
    data_file = FileField('Data file:', [validators.Required()])
    dataset_desc = TextAreaField('Description:', [validators.optional(), validators.length(max=500)])
    submit = SubmitField('Upload Data')

class SearchParamsForm(Form):

    ''' SearchParamsForm is a WTForm Form object for proteomic search parameters
    '''

    search_name = StringField(  'Search name',
                                [validators.Required(), validators.length(max=60)], 
                                )

    diff_search_options = StringField(  'Differential Search Options (diffmods)', 
                                        default='15.9949 M', 
                                        )
    diff_search_Nterm = StringField(    'N-terminal diffmod',
                                        default=None,
                                        )
    diff_search_Cterm = StringField(    'C-terminal diffmod',
                                        default=None,
                                        )
    default_mongodb_uri = ','.join(('imsb0501:27018', 
                                    'imsb0515:27018', 
                                    'imsb0601:27018', 
                                    'imsb0615:27018', 
                                    'node0097:27018', 
                                    'node0113:27018', 
                                    'node0129:27018', 
                                    'node0145:27018', 
                                    'node0401:27018', 
                                    'node0411:27018', 
                                    'node0421:27018', 
                                    'node0431:27018', 
                                    'node0441:27018', 
                                    'node0451:27018', 
                                    'node0461:27018', 
                                    'node0471:27018', 
                                    'node0481:27018', 
                                    'node0491:27018', 
                                    'node0501:27018', 
                                    'node0511:27018', 
                                    'node0521:27018', 
                                    'node0531:27018', 
                                    'node0541:27018', 
                                    'node0551:27018', 
                                    'node0561:27018', 
                                    'node0571:27018', 
                                    'node0581:27018', 
                                    'node0591:27018', 
                                    'node0601:27018', 
                                    'node0617:27018', 
                                    'node0633:27018', 
                                    'node0649:27018', 
                                    'node0665:27018', 
                                    'node0681:27018', 
                                    'node0922:27018', 
                                    'node0937:27018', 
                                    'node0953:27018', 
                                    'node0969:27018', 
                                    'node0985:27018', 
                                    'node1001:27018', 
                                    'nodea1301:27018', 
                                    'nodea1331:27018', 
                                    'nodea1401:27018', 
                                    'nodea1431:27018', 
                                    ))
    mongodb_uri = StringField( 'MongoDB URI', 
                                default='mongodb://'+default_mongodb_uri, 
                                )
    is_sharded = BooleanField(  'Database is sharded',
                                default=True, 
                                )
    massdb_name = StringField(  'MassDB database',
                                default='MassDB_072114', 
                                )
    massdbcoll = StringField(   'MassDB collection',
                                default='MassDB_072114', 
                                )
    use_seqdb = BooleanField(   'Use SeqDB to lookup parent proteins for identified peptides', 
                                default=True, 
                                )
    seqdb_name = StringField(   'SeqDB database name',
                                default='SeqDB_072114', 
                                )
    seqdbcoll = StringField(    'SeqDB collection',
                                default='SeqDB_072114', 
                                )
    use_protdb = BooleanField(  'Use ProtDB to lookup Protein ID values', 
                                default=False, 
                                )
    protdb_name = StringField(  'ProtDB database name',
                                default='ProtDB_072114', 
                                )
    protdbcoll = StringField(   'ProtDB collection',
                                default='ProtDB_072114', 
                                )
    blazmass_jar = StringField( 'Path to Blazmass JAR', 
                                default='/gpfs/home/gstupp/blazmass/blazmass.jar', 
                                )
    dtaselect_classpath = StringField(   'Path to DTASelect (classpath)', 
                                    default='/gpfs/home/gstupp/DTASelect2', 
                                    )
    temp = StringField(        'Temporary directory name', 
                                default='dummy', 
                                )
    verbose = BooleanField(    'Verbose logging', 
                                default=True, 
                                )
    ppm_peptide_mass_tolerance = DecimalField(  'ppm precursor (peptide) mass tolerance',
                                                places=1, 
                                                default=30.0
                                                )
    ppm_fragment_ion_tolerance = DecimalField(  'ppm fragment ion tolerance', 
                                                places=1, 
                                                default=50.0, 
                                                )
    ppm_fragment_ion_tolerance_high = BooleanField( 'ppm fragment ion tolerance/high',
                                                    default=False, 
                                                    )

    server_preset = StringField(    'Computing cluster',
                                    default='garibaldi', 
                                    )
    numcores = IntegerField(    '# cores per job',
                                    default=4, 
                                    )
    numthreads = IntegerField(  '# search threads per job',
                                    default=4, 
                                    )
    walltime = IntegerField(    '# hours walltime per job',
                                    default=8, 
                                    )
    split_n = IntegerField(     '# files to split each MS2 file into',
                                    default=10, 
                                    )

    sfp = DecimalField( 'Peptide False Discovery Rate',
                        places=2,
                        default=0.01, 
                        )
    ppp = IntegerField( '# required peptides per protein',
                        default=2, 
                        )
    use_job_spacing = BooleanField(    'Use job submission spacing', 
                                )
    job_spacing = IntegerField( '# minutes to wait between submitting jobs',
                                default=1, 
                                )
    job_spacing_init = IntegerField(    '# jobs to submit initially (if using job_spacing)',
                                        default=0, 
                                        )
    submit = SubmitField('Run Search')

biome/__init__.py
#!/usr/bin/env python3

import os
import logging
from flask import ( Blueprint, 
                    Flask, 
                    render_template, 
                    request, 
                    )
from celery import Celery
from flask.ext.sqlalchemy import SQLAlchemy
from flask_wtf import Form
from biome.config import set_config
from logging.handlers import RotatingFileHandler

api = Blueprint('api', __name__)
data = Blueprint('data', __name__)
search = Blueprint('search', __name__)

app = Flask(__name__, static_folder='static')
logging_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

info_handler = RotatingFileHandler('log_biome_info.log', maxBytes=10000, backupCount=1)
info_handler.setLevel(logging.INFO)
info_handler.setFormatter(logging_formatter)

error_handler = RotatingFileHandler('log_biome_error.log', maxBytes=10000, backupCount=1)
error_handler.setLevel(logging.ERROR)
error_handler.setFormatter(logging_formatter)

app.logger.addHandler(info_handler)
app.logger.addHandler(error_handler)
set_config(app)

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'], backend=app.config['CELERY_RESULT_BACKEND'])

db = SQLAlchemy(app)

import biome.views
import biome.models

@app.errorhandler(404)
def not_found(error):
    wrong_url = request.path
    return render_template('404.html', wrong_url=wrong_url), 404

app.register_blueprint(api, url_prefix='/api')
app.register_blueprint(data, url_prefix='/data')
app.register_blueprint(search, url_prefix='/search')

biome/views.py
#!/usr/bin/env python3

import json
from flask import ( Blueprint, 
                    current_app, 
                    jsonify, 
                    render_template, 
                    request, 
                    )
from biome import ( app, 
                    api, 
                    data, 
                    db, 
                    models, 
                    views_api, 
                    views_documents, 
                    views_helpers, 
                    views_plots, 
                    views_searches, 
                    )

## API/Blueprint:

@api.route('/json')
def json_api():

    sample_dictionary = {'name': 'sandip', 'height': 68}

    return jsonify(sample_dictionary)

## regular view functions for app

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/API_test')
def test_API():
    json_obj = views_helpers.get_json_response('api.json_api')
    json_obj = json.loads(json_obj)
    
    # example modifying new dict
    json_obj['new'] = 3
    
    return json.dumps(json_obj)

@app.route('/mongos_status')
def mongos_status():

    ''' View that retrieves data for mongos response times
        (uses API view mongos_status)
    '''

    return render_template('mongos_status.html', 
                            )

biome/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Biome{% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block head_additions %}
        {% endblock %}
    </head>

    <body>
        {% block navbar %}

        {% set navigation_bar = [
            (url_for('index'), 'index', 'Home'),
            ('/search/', 'search', 'Search ComPIL'),
            ('/build/', 'build', 'Build ComPIL'), 
            (url_for('data.document_index'), 'view', 'View Data'), 
            ('/analyze/', 'analyze', 'Analyze Data'), 
        ] -%}

        {% set active_page = active_page|default('index') -%}

        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('index') }}">Biome</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% for href, id, caption in navigation_bar %}
                <li{% if id == active_page %} class="active"{% endif%}>
                  <a href="{{ href|e }}">{{ caption|e }}</a>
                </li>
                {% endfor %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tools <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Database status</a></li>
                    <li><a href="#">Another action</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Upload a file</a></li>
                    <li class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <!-- <li><a href="#">Link</a></li> -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Links <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="http://www.scripps.edu/wolan">Wolan Lab</a></li>
                    <li><a href="http://wolands.scripps.edu/">WolanDS</a></li>
                    <li class="divider"></li>
                    <li><a href="http://sulab.org/">Su Lab</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>



        <div class="container">
          {% for message in get_flashed_messages() %}
          <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
          </div>
          {% endfor %}
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

biome/templates/embed.html
{% extends "base.html" %}

{% block head_additions %}
{{ plot_resources|indent(4)|safe }}
{{ plot_script|indent(4)|safe }}
{% endblock %}

{% block content %}

    <! A simple form for changing the graph>
    <p> Select your settings: </p>
    <form name="color_button" method='GET'>
        Color: 
        <select name="color">
            <option value="Red">Red</option>
            <option value="Green">Green</option>
            <option value="Blue">Blue</option>
            <option selected="selected" value="Black">Black</option>
        </select>
        <br>
        From:
        <input type="text" name="_from" value="{{ _from }}">
        <br>
        To:
        <input type="text" name="to" value="{{ to }}">
        <br>
        <button type="submit">Submit</button>
    </form>
    {{ plot_div|indent(4)|safe }}
    <p> Demonstrates some very simple embedding into a webpage</p>

{% endblock %}

biome/templates/index.html
{% extends "base.html" %}

{% block title %} - Main Page{% endblock %}

{% block content %}
<h1>Biome</h1>
<p class="lead">a collection of tools for metaproteomic data analysis</p>

<div class="row">
  <div class="col-md-3 text-center">
    <a href="#" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-search" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Search ComPIL&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="#" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-cloud-upload" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Build ComPIL&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="{{ url_for('data.document_index') }}" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-th-list" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;View Data&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="#" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-equalizer" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Analyze Data&nbsp;
    </a>
  </div>
</div>
{% endblock %}

biome/templates/mongos_status.html
{% extends "base.html" %}
{% set active_page = None %}

{% block title %} - DB Status (cluster mongos){% endblock %}

{% block content %}
<h1>Database status</h1>
<p class="lead">cluster mongos query router status</p>  

<!-- <div class="row display-table">
    <div class="col-md-7 display-cell">
        <h3>Recent Datasets</h3>
    </div>
</div> -->

<div class="row">
    <div class="col-md-3" id="refreshButtonDiv">
        <button type="button" class="btn btn-primary" id="refreshButton">Refresh</button>
    </div>
    <div class="col-md-3" id="progressBarDiv" style="display:none;">
        <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            </div>
        </div>
    </div>
</div>


<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center">mongos host:port</th>
            <th class="text-center">query time (ms)</th>
            <th class="text-center">last updated</th>
        </tr>
    </thead>

    <!-- for loop here -->
    <tr>
        <td class="text-center">mongos_data</td>
        <td class="text-center">querytime_data</td>
        <td class="text-center">lastupdated_data</td>
    </tr>
    <!-- endfor -->
</table>

<br>

<script src="{{ url_for('static', filename='js/biome.js') }}"></script>

<script>

// Refresh status
$(function() {
    $('#refreshButton').click(function(event) {
        event.preventDefault();

        var mongosAPIURL = "{{ url_for('api.mongos_status') }}";

        $.ajax({
            type: 'POST',
            url: mongosAPIURL,
        }).done(function(data, textStatus, jqXHR){
            console.log(data);
            console.log(textStatus);
            console.log(jqXHR);
            console.log('Submitted refresh tasks');

            if (data['task_id']) {
                $('#refreshButton').html('Refreshing...');
                $('#refreshButton').addClass('disabled');
                $("#progressBarDiv").show();
            }
            else {
                $("#progressBarDiv").html('Error submitting task');
            }

        }).fail(function(data){
            $("#progressBarDiv").html('Error submitting task');
        });
    });
});

</script>


{% endblock %}